service: myserverlessproject

provider:
    name: aws
    runtime: nodejs16.x
    profile: serverlessUser
    region: eu-west-1
    environment:
        USERS_TABLE: ${self:custom.usersTable}
        BLOGS_TABLE: ${self:custom.blogsTable}
        BLOG_COMMENTS_TABLE: ${self:custom.blogCommentsTable}
        PODCASTS_TABLE: ${self:custom.podcastsTable}
        PODCAST_COMMENTS_TABLE: ${self:custom.podcastCommentsTable}
        LISTINGS_TABLE: ${self:custom.listingsTable}
        JWT_SECRET: ${file(./env.js):JWT_SECRET}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:GetItem
                      - dynamodb:BatchGetItem
                      - dynamodb:PutItem
                      - dynamodb:Query
                      - dynamodb:Scan
                  Resource:
                      - !GetAtt UsersTable.Arn
                      - !Sub "${UsersTable.Arn}/index/*"
                      - !GetAtt BlogsTable.Arn
                      - !GetAtt BlogCommentsTable.Arn
                      - !Sub "${BlogCommentsTable.Arn}/index/*"
                      - !GetAtt PodcastsTable.Arn
                      - !GetAtt PodcastCommentsTable.Arn
                      - !Sub "${PodcastCommentsTable.Arn}/index/*"
                      - !GetAtt ListingsTable.Arn

plugins:
    - serverless-webpack

package:
    individually: true

custom:
    usersTable: myserverlessproject-users-${sls:stage}
    blogsTable: myserverlessproject-blogs-${sls:stage}
    blogCommentsTable: myserverlessproject-blog-comments-${sls:stage}
    podcastsTable: myserverlessproject-podcasts-${sls:stage}
    podcastCommentsTable: myserverlessproject-podcast-comments-${sls:stage}
    listingsTable: myserverlessproject-listings-${sls:stage}

functions:
    getUsers:
        handler: lambdas/getUsers.handler
        events:
            - http:
                path: get-users/{ID}
                method: GET
                cors: true
    getBlogs:
        handler: lambdas/getBlogs.handler
        events:
            - http:
                path: get-blogs/
                method: GET
                cors: true
    getListings:
        handler: lambdas/getListings.handler
        events:
            - http:
                path: get-listings/
                method: GET
                cors: true
    getPodcasts:
        handler: lambdas/getPodcasts.handler
        events:
            - http:
                path: get-podcasts/
                method: GET
                cors: true
    register:
        handler: lambdas/register.handler
        events:
            - http:
                path: register/
                method: POST
                cors: true
    login:
        handler: lambdas/login.handler
        events:
            - http:
                path: login/
                method: POST
                cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: myserverlessprojectuploadbucket-768344
        UsersTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.usersTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: email
                      AttributeType: S
                    - AttributeName: username
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: EmailIndex
                      KeySchema:
                          - AttributeName: email
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                    - IndexName: UsernameIndex
                      KeySchema:
                          - AttributeName: username
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
        BlogsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.blogsTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
        BlogCommentsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.blogCommentsTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: N
                    - AttributeName: blogId
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: BlogIdIndex
                      KeySchema:
                          - AttributeName: blogId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
        PodcastsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.podcastsTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
        PodcastCommentsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.podcastCommentsTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: N
                    - AttributeName: episodeId
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: EpisodeIdIndex
                      KeySchema:
                          - AttributeName: episodeId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
        ListingsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.listingsTable}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
