const data = [
  {
    "id": "8026058267",
    "firstName": "Chase",
    "lastName": "Shields",
    "username": "cshields",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cshields@drino.com",
    "avatar": "https://i.pravatar.cc/50?img=1",
    "description": "ðŸ• Phasellus in felis. Suspendisse ornare consequat lectus. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "job_title": null,
    "is_employee": true,
    "is_admin": true,
    "location": "Denver, CO",
    "joined_date": "Jan 29, 2023",
    "education": "MBA",
    "work": "Data Analyst"
  },
  {
    "id": "8115244554",
    "firstName": "Fabian",
    "lastName": "Duplock",
    "username": "fduplock1",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "fduplock1@a8.net",
    "avatar": "https://i.pravatar.cc/50?img=2",
    "description": "In hac habitasse platea dictumst. Morbi porttitor lorem id ligula. Morbi sem mauris, laoreet ut, rhoncus aliquet. ðŸ¶",
    "job_title": null,
    "is_employee": true,
    "is_admin": true,
    "location": "Stockholm, SE",
    "joined_date": "Aug 25, 2024",
    "education": "Some College",
    "work": "Graphic Designer"
  },
  {
    "id": "6068071324",
    "firstName": "Corabelle",
    "lastName": "MacAloren",
    "username": "cmacaloren2",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cmacaloren2@tinypic.com",
    "avatar": "https://i.pravatar.cc/50?img=3",
    "description": "Fusce posuere felis sed lacus. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Copenhagen, DK",
    "joined_date": "Nov 10, 2022",
    "education": "MBA",
    "work": "Full-Stack Developer"
  },
  {
    "id": "0191971308",
    "firstName": "Mireielle",
    "lastName": "Banthorpe",
    "username": "mbanthorpe3",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mbanthorpe3@comsenz.com",
    "avatar": "https://i.pravatar.cc/50?img=4",
    "description": "ðŸ“¸ Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Barcelona, ES",
    "joined_date": "Dec 18, 2022",
    "education": "B.S. Information Systems",
    "work": "High School Teacher"
  },
  {
    "id": "8289969457",
    "firstName": "Christiana",
    "lastName": "Furness",
    "username": "cfurness4",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cfurness4@imdb.com",
    "avatar": "https://i.pravatar.cc/50?img=5",
    "description": "ðŸŽ§ Vestibulum ante ipsum primis in faucibus orci luctus. Curabitur gravida nisi at nibh. Morbi non quam nec dui luctus rutrum. ðŸ§¡",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Minneapolis, MN",
    "joined_date": "Mar 22, 2025",
    "education": "M.A. Journalism",
    "work": "Customer Success Manager"
  },
  {
    "id": "0895688646",
    "firstName": "Otes",
    "lastName": "Wyllcock",
    "username": "owyllcock5",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "owyllcock5@bing.com",
    "avatar": "https://i.pravatar.cc/50?img=6",
    "description": "Maecenas tincidunt lacus at velit. Donec semper sapien a libero. Proin eu mi.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Salt Lake City, UT",
    "joined_date": "Aug 21, 2023",
    "education": "Ph.D. Economics",
    "work": "Photographer"
  },
  {
    "id": "7405038433",
    "firstName": "Ruttger",
    "lastName": "Archbutt",
    "username": "rarchbutt6",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "rarchbutt6@eventbrite.com",
    "avatar": "https://i.pravatar.cc/50?img=7",
    "description": "ðŸŒ± Duis mattis egestas metus. Vivamus vel nulla eget eros elementum pellentesque. Donec semper sapien a libero. Sed ante. ðŸŽ¨",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Dec 18, 2023",
    "education": "Coding Bootcamp Grad",
    "work": "Sales Associate"
  },
  {
    "id": "6248120293",
    "firstName": "Wenda",
    "lastName": "Couldwell",
    "username": "wcouldwell7",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "wcouldwell7@cafepress.com",
    "avatar": "https://i.pravatar.cc/50?img=8",
    "description": "Vitae mattis nibh ligula nec sem. Phasellus in felis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. ðŸ§¡",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Feb 26, 2024",
    "education": "Self-taught",
    "work": "Photographer"
  },
  {
    "id": "5750908763",
    "firstName": "Maggi",
    "lastName": "Stephenson",
    "username": "mstephenson8",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mstephenson8@phpbb.com",
    "avatar": "https://i.pravatar.cc/50?img=9",
    "description": "ðŸ”ï¸ Proin eu mi. Aliquam non mauris. Maecenas leo odio, condimentum id, luctus nec. Morbi ut odio.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Portland, OR",
    "joined_date": "Dec 6, 2025",
    "education": "B.A. Communications",
    "work": "IT Support Specialist"
  },
  {
    "id": "3377731490",
    "firstName": "Carmelle",
    "lastName": "Woolen",
    "username": "cwoolen9",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cwoolen9@amazonaws.com",
    "avatar": "https://i.pravatar.cc/50?img=10",
    "description": "ðŸ“š Nulla dapibus dolor vel est. Donec odio justo, suscipit a, feugiat et, eros. Vivamus vel nulla eget eros elementum pellentesque. Vivamus tortor.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Minneapolis, MN",
    "joined_date": "Jun 20, 2025",
    "education": "B.S. Finance",
    "work": "Retired"
  },
  {
    "id": "7202145235",
    "firstName": "Karlik",
    "lastName": "Reynoollds",
    "username": "kreynoolldsa",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "kreynoolldsa@bigcartel.com",
    "avatar": "https://i.pravatar.cc/50?img=11",
    "description": "ðŸŒ± Pellentesque viverra pede ac diam. Aenean sit amet justo. Nulla dapibus dolor vel est.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Melbourne, AU",
    "joined_date": "Jul 23, 2022",
    "education": "B.A. Marketing",
    "work": "Barista & Artist"
  },
  {
    "id": "3556668378",
    "firstName": "Thomasin",
    "lastName": "Glasner",
    "username": "tglasnerb",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tglasnerb@acquirethisname.com",
    "avatar": "https://i.pravatar.cc/50?img=12",
    "description": "ðŸ“š Morbi sem mauris, laoreet ut, rhoncus aliquet. Donec odio justo, suscipit a, feugiat et, eros. Maecenas leo odio, condimentum id, luctus nec.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Apr 29, 2025",
    "education": "Ph.D. Economics",
    "work": "Operations Manager"
  },
  {
    "id": "6600119144",
    "firstName": "Helenka",
    "lastName": "Bust",
    "username": "hbustc",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "hbustc@nature.com",
    "avatar": "https://i.pravatar.cc/50?img=13",
    "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet. Maecenas leo odio, condimentum id, luctus nec.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Atlanta, GA",
    "joined_date": "Jan 29, 2026",
    "education": "High School Diploma",
    "work": "Photographer"
  },
  {
    "id": "7522682096",
    "firstName": "Tiphani",
    "lastName": "Pannaman",
    "username": "tpannamand",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tpannamand@vinaora.com",
    "avatar": "https://i.pravatar.cc/50?img=14",
    "description": "Cras non velit nec nisi vulputate nonummy. Nunc rhoncus dui vel sem. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "New Orleans, LA",
    "joined_date": "Jun 6, 2024",
    "education": "M.S. Data Science",
    "work": "Between Jobs"
  },
  {
    "id": "1550871153",
    "firstName": "Seth",
    "lastName": "Taylder",
    "username": "stayldere",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "stayldere@state.gov",
    "avatar": "https://i.pravatar.cc/50?img=15",
    "description": "ðŸ• Maecenas tincidunt lacus at velit. Nullam porttitor lacus at turpis. Cras pellentesque volutpat dui. In hac habitasse platea dictumst.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Nashville, TN",
    "joined_date": "Nov 6, 2025",
    "education": "B.S. Mechanical Engineering",
    "work": "Registered Nurse"
  },
  {
    "id": "1116352575",
    "firstName": "Filmore",
    "lastName": "Truse",
    "username": "ftrusef",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "ftrusef@huffingtonpost.com",
    "avatar": "https://i.pravatar.cc/50?img=16",
    "description": "â˜• Donec posuere metus vitae ipsum. Morbi ut odio.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Denver, CO",
    "joined_date": "Sep 22, 2023",
    "education": "B.A. Communications",
    "work": "Registered Nurse"
  },
  {
    "id": "8213268032",
    "firstName": "Rich",
    "lastName": "Ondrak",
    "username": "rondrakg",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "rondrakg@so-net.ne.jp",
    "avatar": "https://i.pravatar.cc/50?img=17",
    "description": "ðŸ§¡ Vestibulum ante ipsum primis in faucibus orci luctus. Morbi ut odio. Cras non velit nec nisi vulputate nonummy. Quisque id justo sit amet sapien dignissim vestibulum.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boise, ID",
    "joined_date": "Mar 14, 2024",
    "education": "B.A. Psychology",
    "work": "Remote Contractor"
  },
  {
    "id": "4499783224",
    "firstName": "Basil",
    "lastName": "Haimes",
    "username": "bhaimesh",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bhaimesh@artisteer.com",
    "avatar": "https://i.pravatar.cc/50?img=18",
    "description": "Proin eu mi. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. ðŸŒ",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Prague, CZ",
    "joined_date": "Dec 23, 2024",
    "education": "B.A. Communications",
    "work": "Real Estate Agent"
  },
  {
    "id": "3554897809",
    "firstName": "Gregoire",
    "lastName": "Balazot",
    "username": "gbalazoti",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "gbalazoti@washingtonpost.com",
    "avatar": "https://i.pravatar.cc/50?img=19",
    "description": "âœ¨ Aliquam non mauris. Nulla tellus. Molestie sed, justo.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Pittsburgh, PA",
    "joined_date": "Nov 25, 2022",
    "education": "B.S. Business Administration",
    "work": "Marketing Lead"
  },
  {
    "id": "2839931028",
    "firstName": "Obediah",
    "lastName": "Liven",
    "username": "olivenj",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "olivenj@gmpg.org",
    "avatar": "https://i.pravatar.cc/50?img=20",
    "description": "Nullam porttitor lacus at turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. Cras pellentesque volutpat dui.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Portland, OR",
    "joined_date": "Feb 18, 2025",
    "education": "B.A. Communications",
    "work": "Software Engineer"
  },
  {
    "id": "0814447180",
    "firstName": "Gunilla",
    "lastName": "Storr",
    "username": "gstorr0",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "gstorr0@shareasale.com",
    "avatar": "https://i.pravatar.cc/50?img=21",
    "description": "ðŸ¥‘ Nunc rhoncus dui vel sem. Cras non velit nec nisi vulputate nonummy.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Pittsburgh, PA",
    "joined_date": "Feb 3, 2023",
    "education": "B.A. Communications",
    "work": "UX Researcher"
  },
  {
    "id": "0212326323",
    "firstName": "Cody",
    "lastName": "Draycott",
    "username": "cdraycott1",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cdraycott1@yellowbook.com",
    "avatar": "https://i.pravatar.cc/50?img=22",
    "description": "Molestie sed, justo. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Nov 2, 2023",
    "education": "B.A. Communications",
    "work": "Operations Manager"
  },
  {
    "id": "8890121960",
    "firstName": "Donelle",
    "lastName": "Casari",
    "username": "dcasari2",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dcasari2@imdb.com",
    "avatar": "https://i.pravatar.cc/50?img=23",
    "description": "ðŸ• Molestie sed, justo. Phasellus in felis. Vivamus vel nulla eget eros elementum pellentesque. Donec posuere metus vitae ipsum.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boise, ID",
    "joined_date": "Jan 11, 2022",
    "education": "M.S. Data Science",
    "work": "Project Coordinator"
  },
  {
    "id": "1574015342",
    "firstName": "Tibold",
    "lastName": "Blainey",
    "username": "tblainey3",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tblainey3@nps.gov",
    "avatar": "https://i.pravatar.cc/50?img=24",
    "description": "ðŸŒ¸ Vitae mattis nibh ligula nec sem. Donec odio justo, suscipit a, feugiat et, eros. Aliquam non mauris.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Copenhagen, DK",
    "joined_date": "May 5, 2026",
    "education": "Some College",
    "work": "Customer Success Manager"
  },
  {
    "id": "8958131918",
    "firstName": "Teodoor",
    "lastName": "Crossby",
    "username": "tcrossby4",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tcrossby4@stumbleupon.com",
    "avatar": "https://i.pravatar.cc/50?img=25",
    "description": "ðŸŽ¯ Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Fusce posuere felis sed lacus. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Barcelona, ES",
    "joined_date": "Jul 17, 2023",
    "education": "B.S. Business Administration",
    "work": "Graphic Designer"
  },
  {
    "id": "2606404292",
    "firstName": "Moselle",
    "lastName": "Dewerson",
    "username": "mdewerson5",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mdewerson5@storify.com",
    "avatar": "https://i.pravatar.cc/50?img=26",
    "description": "Donec posuere metus vitae ipsum. Phasellus in felis. Nulla dapibus dolor vel est. Praesent id massa id nisl venenatis lacinia.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Vienna, AT",
    "joined_date": "Dec 29, 2023",
    "education": "B.S. Computer Science",
    "work": "Data Analyst"
  },
  {
    "id": "2161646489",
    "firstName": "Emmet",
    "lastName": "Whetson",
    "username": "ewhetson6",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "ewhetson6@prlog.org",
    "avatar": "https://i.pravatar.cc/50?img=27",
    "description": "ðŸ§¡ Nunc rhoncus dui vel sem. Vestibulum ante ipsum primis in faucibus orci luctus.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Atlanta, GA",
    "joined_date": "Aug 30, 2025",
    "education": "B.S. Finance",
    "work": "Small Business Owner"
  },
  {
    "id": "7534821168",
    "firstName": "Clair",
    "lastName": "Gipps",
    "username": "cgipps7",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cgipps7@discuz.net",
    "avatar": "https://i.pravatar.cc/50?img=28",
    "description": "ðŸŒ± Suspendisse ornare consequat lectus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Nulla tellus. Sed ante.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Nov 24, 2025",
    "education": "Self-taught",
    "work": "Freelance Designer"
  },
  {
    "id": "5356344817",
    "firstName": "Dwain",
    "lastName": "Eberz",
    "username": "deberz8",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "deberz8@latimes.com",
    "avatar": "https://i.pravatar.cc/50?img=29",
    "description": "ðŸŒ± Nulla ac enim. Praesent id massa id nisl venenatis lacinia. Morbi ut odio. ðŸŒž",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boston, MA",
    "joined_date": "Nov 15, 2023",
    "education": "Ph.D. Economics",
    "work": "Sales Associate"
  },
  {
    "id": "2944926668",
    "firstName": "Devin",
    "lastName": "Vockins",
    "username": "dvockins9",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dvockins9@wunderground.com",
    "avatar": "https://i.pravatar.cc/50?img=30",
    "description": "ðŸ• Aenean sit amet justo. In hac habitasse platea dictumst. ðŸŒ",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boise, ID",
    "joined_date": "Aug 29, 2025",
    "education": "B.S. Information Systems",
    "work": "Founder, Startup Co."
  },
  {
    "id": "9107132851",
    "firstName": "Gisele",
    "lastName": "Fruchter",
    "username": "gfruchtera",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "gfruchtera@mysql.com",
    "avatar": "https://i.pravatar.cc/50?img=31",
    "description": "ðŸŽ¯ Phasellus in felis. Duis bibendum. Cras non velit nec nisi vulputate nonummy. Proin eu mi.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Jul 10, 2022",
    "education": "B.S. Finance",
    "work": "Data Analyst"
  },
  {
    "id": "5894281569",
    "firstName": "Julianne",
    "lastName": "Burwin",
    "username": "jburwinb",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jburwinb@domainmarket.com",
    "avatar": "https://i.pravatar.cc/50?img=32",
    "description": "Maecenas tincidunt lacus at velit. Duis bibendum. Vivamus vel nulla eget eros elementum pellentesque.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Melbourne, AU",
    "joined_date": "Feb 6, 2025",
    "education": "Trade School, Electrical",
    "work": "IT Support Specialist"
  },
  {
    "id": "9560788341",
    "firstName": "Dorette",
    "lastName": "Hounsom",
    "username": "dhounsomc",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dhounsomc@t.co",
    "avatar": "https://i.pravatar.cc/50?img=33",
    "description": "Aliquam non mauris. Suspendisse ornare consequat lectus. Morbi ut odio. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Salt Lake City, UT",
    "joined_date": "Mar 8, 2022",
    "education": "B.A. Psychology",
    "work": "Photographer"
  },
  {
    "id": "5198457583",
    "firstName": "Sullivan",
    "lastName": "Worswick",
    "username": "sworswickd",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "sworswickd@smugmug.com",
    "avatar": "https://i.pravatar.cc/50?img=34",
    "description": "Vivamus tortor. Donec odio justo, suscipit a, feugiat et, eros.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "New Orleans, LA",
    "joined_date": "May 28, 2023",
    "education": "B.S. Computer Science",
    "work": "Registered Nurse"
  },
  {
    "id": "4291696763",
    "firstName": "Mack",
    "lastName": "Greaves",
    "username": "mgreavese",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mgreavese@telegraph.co.uk",
    "avatar": "https://i.pravatar.cc/50?img=35",
    "description": "ðŸ¥‘ Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Praesent id massa id nisl venenatis lacinia.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boise, ID",
    "joined_date": "May 30, 2025",
    "education": "B.S. Mechanical Engineering",
    "work": "Remote Contractor"
  },
  {
    "id": "7758822455",
    "firstName": "Ailbert",
    "lastName": "Tranmer",
    "username": "atranmerf",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "atranmerf@arizona.edu",
    "avatar": "https://i.pravatar.cc/50?img=36",
    "description": "ðŸŒ± Curabitur gravida nisi at nibh. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Apr 18, 2022",
    "education": "B.S. Mechanical Engineering",
    "work": "Software Engineer"
  },
  {
    "id": "4596430708",
    "firstName": "Jennie",
    "lastName": "Echallier",
    "username": "jechallierg",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jechallierg@opera.com",
    "avatar": "https://i.pravatar.cc/50?img=37",
    "description": "Maecenas tincidunt lacus at velit. Nulla tellus. Curabitur gravida nisi at nibh. ðŸŒž",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Feb 16, 2025",
    "education": "Self-taught",
    "work": "Graphic Designer"
  },
  {
    "id": "5415214205",
    "firstName": "Blondie",
    "lastName": "Yitshak",
    "username": "byitshakh",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "byitshakh@baidu.com",
    "avatar": "https://i.pravatar.cc/50?img=38",
    "description": "ðŸ¶ In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem. Quisque id justo sit amet sapien dignissim vestibulum.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Denver, CO",
    "joined_date": "Jun 13, 2022",
    "education": "B.A. English Literature",
    "work": "Product Manager @ Acme"
  },
  {
    "id": "6755190597",
    "firstName": "Jesica",
    "lastName": "Angless",
    "username": "banglessi",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "banglessi@storify.com",
    "avatar": "https://i.pravatar.cc/50?img=39",
    "description": "Vitae mattis nibh ligula nec sem. Vivamus tortor. ðŸŒ¸",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Auckland, NZ",
    "joined_date": "Apr 26, 2024",
    "education": "B.S. Biology",
    "work": "Content Strategist"
  },
  {
    "id": "3095107488",
    "firstName": "Ortensia",
    "lastName": "Baird",
    "username": "obairdj",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "obairdj@domainmarket.com",
    "avatar": "https://i.pravatar.cc/50?img=40",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vitae mattis nibh ligula nec sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Jul 5, 2022",
    "education": "High School Diploma",
    "work": "Graphic Designer"
  },
  {
    "id": "9272232225",
    "firstName": "Ellary",
    "lastName": "Floyde",
    "username": "efloyde0",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "efloyde0@blogger.com",
    "avatar": "https://i.pravatar.cc/50?img=41",
    "description": "ðŸš€ Phasellus in felis. Vivamus tortor.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Kansas City, MO",
    "joined_date": "Mar 7, 2022",
    "education": "B.A. Communications",
    "work": "Independent Consultant"
  },
  {
    "id": "9813393633",
    "firstName": "Jacintha",
    "lastName": "Chatel",
    "username": "jchatel1",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jchatel1@last.fm",
    "avatar": "https://i.pravatar.cc/50?img=42",
    "description": "In hac habitasse platea dictumst. Phasellus in felis. Nulla tellus. ðŸŽ¨",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Nashville, TN",
    "joined_date": "Aug 24, 2024",
    "education": "B.S. Computer Science",
    "work": "High School Teacher"
  },
  {
    "id": "2721784414",
    "firstName": "Willy",
    "lastName": "Iffe",
    "username": "wiffe2",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "wiffe2@msn.com",
    "avatar": "https://i.pravatar.cc/50?img=43",
    "description": "Cras pellentesque volutpat dui. Nam dui. Duis mattis egestas metus. Donec odio justo, suscipit a, feugiat et, eros.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Vancouver, BC",
    "joined_date": "Jun 4, 2024",
    "education": "B.S. Computer Science",
    "work": "UX Researcher"
  },
  {
    "id": "1215090741",
    "firstName": "Fredek",
    "lastName": "Ivanilov",
    "username": "fivanilov3",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "fivanilov3@shinystat.com",
    "avatar": "https://i.pravatar.cc/50?img=44",
    "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Edinburgh, UK",
    "joined_date": "Apr 1, 2022",
    "education": "M.Ed. Education",
    "work": "Real Estate Agent"
  },
  {
    "id": "0197158659",
    "firstName": "Leanor",
    "lastName": "Boam",
    "username": "lboam4",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "lboam4@patch.com",
    "avatar": "https://i.pravatar.cc/50?img=45",
    "description": "Cras non velit nec nisi vulputate nonummy. Donec odio justo, suscipit a, feugiat et, eros.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Austin, TX",
    "joined_date": "Jun 22, 2024",
    "education": "M.S. Mechanical Engineering",
    "work": "Between Jobs"
  },
  {
    "id": "0663719139",
    "firstName": "Tull",
    "lastName": "Lengthorn",
    "username": "tlengthorn5",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tlengthorn5@t.co",
    "avatar": "https://i.pravatar.cc/50?img=46",
    "description": "ðŸ• Pellentesque viverra pede ac diam. Nam dui. ðŸ“š",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boston, MA",
    "joined_date": "Jul 8, 2025",
    "education": "M.S. Mechanical Engineering",
    "work": "Founder, Startup Co."
  },
  {
    "id": "1206407241",
    "firstName": "Donny",
    "lastName": "Pighills",
    "username": "dpighills6",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dpighills6@instagram.com",
    "avatar": "https://i.pravatar.cc/50?img=47",
    "description": "Vivamus tortor. Vestibulum ante ipsum primis in faucibus orci luctus. Morbi ut odio. Nam dui.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boston, MA",
    "joined_date": "Jun 5, 2022",
    "education": "MBA",
    "work": "UX Researcher"
  },
  {
    "id": "5861791124",
    "firstName": "Gipsy",
    "lastName": "Hazelgrove",
    "username": "ghazelgrove7",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "ghazelgrove7@howstuffworks.com",
    "avatar": "https://i.pravatar.cc/50?img=48",
    "description": "ðŸŽ¨ Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Nam dui. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Nashville, TN",
    "joined_date": "Jun 22, 2026",
    "education": "Trade School, Electrical",
    "work": "Registered Nurse"
  },
  {
    "id": "2140425645",
    "firstName": "Bunni",
    "lastName": "Branscombe",
    "username": "bbranscombe8",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bbranscombe8@google.nl",
    "avatar": "https://i.pravatar.cc/50?img=49",
    "description": "Vivamus tortor. Nullam porttitor lacus at turpis. Nulla ac enim. ðŸŒ±",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boston, MA",
    "joined_date": "May 7, 2023",
    "education": "B.S. Business Administration",
    "work": "Barista & Artist"
  },
  {
    "id": "5886996924",
    "firstName": "Rita",
    "lastName": "Ruffli",
    "username": "rruffli9",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "rruffli9@dagondesign.com",
    "avatar": "https://i.pravatar.cc/50?img=50",
    "description": "Sed ante. Phasellus in felis.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "San Diego, CA",
    "joined_date": "Mar 9, 2025",
    "education": "M.S. Data Science",
    "work": "Full-Stack Developer"
  },
  {
    "id": "9372882016",
    "firstName": "Reidar",
    "lastName": "Spaight",
    "username": "rspaighta",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "rspaighta@blogger.com",
    "avatar": "https://i.pravatar.cc/50?img=51",
    "description": "Fusce posuere felis sed lacus. Praesent id massa id nisl venenatis lacinia.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Stockholm, SE",
    "joined_date": "Jul 12, 2025",
    "education": "MBA",
    "work": "Real Estate Agent"
  },
  {
    "id": "8140181634",
    "firstName": "Carmine",
    "lastName": "Mathelin",
    "username": "cmathelinb",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cmathelinb@bandcamp.com",
    "avatar": "https://i.pravatar.cc/50?img=52",
    "description": "Molestie sed, justo. Curabitur gravida nisi at nibh. Sed ante. Nullam porttitor lacus at turpis. ðŸ•",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Nashville, TN",
    "joined_date": "Mar 4, 2022",
    "education": "High School Diploma",
    "work": "Full-Stack Developer"
  },
  {
    "id": "5534059000",
    "firstName": "Donn",
    "lastName": "Loud",
    "username": "dloudc",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dloudc@last.fm",
    "avatar": "https://i.pravatar.cc/50?img=53",
    "description": "ðŸ“š Duis bibendum. Donec semper sapien a libero. Donec odio justo, suscipit a, feugiat et, eros.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Chicago, IL",
    "joined_date": "Feb 9, 2023",
    "education": "B.S. Finance",
    "work": "Data Analyst"
  },
  {
    "id": "1266107422",
    "firstName": "Maynord",
    "lastName": "Liebermann",
    "username": "mliebermannd",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mliebermannd@technorati.com",
    "avatar": "https://i.pravatar.cc/50?img=54",
    "description": "ðŸŽ‰ Vestibulum ante ipsum primis in faucibus orci luctus. Donec posuere metus vitae ipsum. Pellentesque viverra pede ac diam. Proin eu mi.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Apr 12, 2022",
    "education": "B.A. Psychology",
    "work": "Registered Nurse"
  },
  {
    "id": "6604656351",
    "firstName": "Basia",
    "lastName": "Bilverstone",
    "username": "bbilverstonee",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bbilverstonee@github.io",
    "avatar": "https://i.pravatar.cc/50?img=55",
    "description": "â˜• Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Columbus, OH",
    "joined_date": "Jun 27, 2024",
    "education": "Self-taught",
    "work": "Data Analyst"
  },
  {
    "id": "1408832792",
    "firstName": "Dene",
    "lastName": "Palfreman",
    "username": "dpalfremanf",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dpalfremanf@spiegel.de",
    "avatar": "https://i.pravatar.cc/50?img=56",
    "description": "ðŸŒž Vitae mattis nibh ligula nec sem. Morbi porttitor lorem id ligula. Nulla tellus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Salt Lake City, UT",
    "joined_date": "May 1, 2022",
    "education": "M.Ed. Education",
    "work": "Barista & Artist"
  },
  {
    "id": "5925505118",
    "firstName": "Kitti",
    "lastName": "Ellicombe",
    "username": "kellicombeg",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "kellicombeg@diigo.com",
    "avatar": "https://i.pravatar.cc/50?img=57",
    "description": "ðŸ“¸ Duis mattis egestas metus. Curabitur gravida nisi at nibh. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Pittsburgh, PA",
    "joined_date": "May 27, 2026",
    "education": "Self-taught",
    "work": "Real Estate Agent"
  },
  {
    "id": "6416078197",
    "firstName": "Janette",
    "lastName": "Andrzejowski",
    "username": "jandrzejowskih",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jandrzejowskih@is.gd",
    "avatar": "https://i.pravatar.cc/50?img=58",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus. Donec posuere metus vitae ipsum. Donec odio justo, suscipit a, feugiat et, eros.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Berlin, DE",
    "joined_date": "Dec 7, 2022",
    "education": "A.A. Graphic Design",
    "work": "Founder, Startup Co."
  },
  {
    "id": "6776308531",
    "firstName": "Cecelia",
    "lastName": "McGonigle",
    "username": "cmcgoniglei",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "cmcgoniglei@g.co",
    "avatar": "https://i.pravatar.cc/50?img=59",
    "description": "ðŸŒž Phasellus in felis. Maecenas leo odio, condimentum id, luctus nec. Molestie sed, justo. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Boston, MA",
    "joined_date": "Dec 3, 2024",
    "education": "A.A. Graphic Design",
    "work": "Sales Associate"
  },
  {
    "id": "6263966297",
    "firstName": "Alexina",
    "lastName": "Snewin",
    "username": "asnewinj",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "asnewinj@cbslocal.com",
    "avatar": "https://i.pravatar.cc/50?img=60",
    "description": "ðŸŒ± Praesent id massa id nisl venenatis lacinia. Nulla tellus. Pellentesque viverra pede ac diam.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Melbourne, AU",
    "joined_date": "Aug 25, 2024",
    "education": "Trade School, Electrical",
    "work": "High School Teacher"
  },
  {
    "id": "9798170036",
    "firstName": "Nadia",
    "lastName": "Ashford",
    "username": "nashford",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "nashford@yahoo.com",
    "avatar": "https://i.pravatar.cc/50?img=61",
    "description": "ðŸŽ¯ Pellentesque viverra pede ac diam. Maecenas leo odio, condimentum id, luctus nec. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem. Cras pellentesque volutpat dui. ðŸ“¸",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Berlin, DE",
    "joined_date": "Aug 11, 2023",
    "education": "B.S. Business Administration",
    "work": "Product Manager @ Acme"
  },
  {
    "id": "0196659427",
    "firstName": "Bao",
    "lastName": "Falcone",
    "username": "bfalcone",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bfalcone@outlook.com",
    "avatar": "https://i.pravatar.cc/50?img=62",
    "description": "ðŸ“š Phasellus in felis. Maecenas tincidunt lacus at velit.",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Seattle, WA",
    "joined_date": "Mar 22, 2022",
    "education": "B.A. English Literature",
    "work": "Barista & Artist"
  },
  {
    "id": "4323815118",
    "firstName": "Jarrah",
    "lastName": "Ashford",
    "username": "jashford",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jashford@outlook.com",
    "avatar": "https://i.pravatar.cc/50?img=63",
    "description": "âœ¨ Donec semper sapien a libero. Pellentesque viverra pede ac diam.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "New Orleans, LA",
    "joined_date": "Dec 9, 2022",
    "education": "B.S. Biology",
    "work": "Data Analyst"
  },
  {
    "id": "6438644364",
    "firstName": "Dashiell",
    "lastName": "Yushchenko",
    "username": "dyushchenko",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dyushchenko@gmail.com",
    "avatar": "https://i.pravatar.cc/50?img=64",
    "description": "ðŸ”¥ In est risus, auctor sed, tristique in, tempus sit amet, sem. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Pellentesque viverra pede ac diam. Morbi ut odio.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Cape Town, ZA",
    "joined_date": "Jan 20, 2026",
    "education": "Trade School, Electrical",
    "work": "High School Teacher"
  },
  {
    "id": "1588639128",
    "firstName": "Halcyon",
    "lastName": "Solberg",
    "username": "hsolberg",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "hsolberg@yahoo.com",
    "avatar": "https://i.pravatar.cc/50?img=65",
    "description": "ðŸš€ Proin eu mi. Cras non velit nec nisi vulputate nonummy. ðŸ•",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Nashville, TN",
    "joined_date": "Apr 4, 2024",
    "education": "Trade School, Electrical",
    "work": "UX Researcher"
  },
  {
    "id": "1660402399",
    "firstName": "Priya",
    "lastName": "Windham",
    "username": "pwindham",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "pwindham@gmail.com",
    "avatar": "https://i.pravatar.cc/50?img=66",
    "description": "Nam dui. Praesent id massa id nisl venenatis lacinia. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Seoul, KR",
    "joined_date": "Jul 26, 2022",
    "education": "B.S. Finance",
    "work": "Customer Success Manager"
  },
  {
    "id": "0202985483",
    "firstName": "Beatrix",
    "lastName": "Quill",
    "username": "bquill",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bquill@yahoo.com",
    "avatar": "https://i.pravatar.cc/50?img=67",
    "description": "Nullam porttitor lacus at turpis. In est risus, auctor sed, tristique in, tempus sit amet, sem. Nulla ac enim. Pellentesque viverra pede ac diam. ðŸ§¡",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Miami, FL",
    "joined_date": "Jul 28, 2024",
    "education": "Self-taught",
    "work": "Remote Contractor"
  },
  {
    "id": "0571112059",
    "firstName": "Soren",
    "lastName": "Sable",
    "username": "ssable",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "ssable@icloud.com",
    "avatar": "https://i.pravatar.cc/50?img=68",
    "description": "Donec odio justo, suscipit a, feugiat et, eros. Vivamus tortor. Morbi porttitor lorem id ligula. ðŸš€",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Barcelona, ES",
    "joined_date": "Sep 4, 2023",
    "education": "B.A. Communications",
    "work": "Product Manager @ Acme"
  },
  {
    "id": "0558680782",
    "firstName": "Dashiell",
    "lastName": "Falcone",
    "username": "dfalcone",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dfalcone@icloud.com",
    "avatar": "https://i.pravatar.cc/50?img=69",
    "description": "Nulla dapibus dolor vel est. Proin eu mi. Vivamus vel nulla eget eros elementum pellentesque. Quisque id justo sit amet sapien dignissim vestibulum. ðŸŒž",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Kansas City, MO",
    "joined_date": "Sep 15, 2023",
    "education": "B.S. Finance",
    "work": "UX Researcher"
  },
  {
    "id": "6747898195",
    "firstName": "Freya",
    "lastName": "Ashford",
    "username": "fashford",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "fashford@outlook.com",
    "avatar": "https://i.pravatar.cc/50?img=70",
    "description": "Nulla ac enim. Vivamus vel nulla eget eros elementum pellentesque.",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Berlin, DE",
    "joined_date": "Dec 9, 2025",
    "education": "Ph.D. Economics",
    "work": "Remote Contractor"
  },
  {
    "id": "5134807157",
    "firstName": "Dashiell",
    "lastName": "Okonkwo",
    "username": "dokonkwo",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dokonkwo@yahoo.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=bi683axz",
    "description": "ðŸŽ‰ Vivamus vel nulla eget eros elementum pellentesque. Quisque id justo sit amet sapien dignissim vestibulum. Nunc rhoncus dui vel sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Auckland, NZ",
    "joined_date": "Oct 25, 2025",
    "education": "B.S. Biology",
    "work": "Content Strategist"
  },
  {
    "id": "0315487830",
    "firstName": "Beatrix",
    "lastName": "Nightingale",
    "username": "bnightingale",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bnightingale@yahoo.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=8TJUo",
    "description": "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Nulla dapibus dolor vel est. Vivamus vel nulla eget eros elementum pellentesque. Duis mattis egestas metus.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Vancouver, BC",
    "joined_date": "Feb 18, 2022",
    "education": "B.S. Mechanical Engineering",
    "work": "Small Business Owner"
  },
  {
    "id": "8758043874",
    "firstName": "Beatrix",
    "lastName": "Zamora",
    "username": "bzamora",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "bzamora@protonmail.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=1Hru",
    "description": "ðŸŒ Aenean sit amet justo. In hac habitasse platea dictumst. In est risus, auctor sed, tristique in, tempus sit amet, sem. Vitae mattis nibh ligula nec sem.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Columbus, OH",
    "joined_date": "Jan 18, 2024",
    "education": "B.A. Communications",
    "work": "Data Analyst"
  },
  {
    "id": "2451229525",
    "firstName": "Xavier",
    "lastName": "Rutledge",
    "username": "xrutledge",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "xrutledge@icloud.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=v6XEK",
    "description": "ðŸŒ¸ Aliquam non mauris. Cras non velit nec nisi vulputate nonummy. ðŸ’¡",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Singapore",
    "joined_date": "Dec 31, 2024",
    "education": "B.S. Mechanical Engineering",
    "work": "Marketing Lead"
  },
  {
    "id": "6060126340",
    "firstName": "MiloÅ¡",
    "lastName": "Nightingale",
    "username": "mnightingale",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mnightingale@icloud.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=NLpI",
    "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Maecenas leo odio, condimentum id, luctus nec. Duis bibendum. ðŸ¥‘",
    "job_title": null,
    "is_employee": true,
    "is_admin": false,
    "location": "Dublin, IE",
    "joined_date": "Aug 10, 2022",
    "education": "B.S. Finance",
    "work": "High School Teacher"
  },
  {
    "id": "6735538072",
    "firstName": "Beatrix",
    "lastName": "Larsen",
    "username": "blarsen",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "blarsen@icloud.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=F4Bs",
    "description": "ðŸŒ Suspendisse ornare consequat lectus. Molestie sed, justo. Cras pellentesque volutpat dui.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Berlin, DE",
    "joined_date": "Aug 2, 2024",
    "education": "B.A. Marketing",
    "work": "UX Researcher"
  },
  {
    "id": "1421793092",
    "firstName": "MiloÅ¡",
    "lastName": "Thorne",
    "username": "mthorne",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "mthorne@protonmail.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=ZDRxY",
    "description": "ðŸŽ¨ Praesent id massa id nisl venenatis lacinia. Nulla dapibus dolor vel est. Donec odio justo, suscipit a, feugiat et, eros. Aliquam non mauris. ðŸ’¡",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Amsterdam, NL",
    "joined_date": "Feb 10, 2025",
    "education": "B.A. English Literature",
    "work": "Small Business Owner"
  },
  {
    "id": "7624372867",
    "firstName": "Junko",
    "lastName": "Nakamura",
    "username": "jnakamura",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jnakamura@yahoo.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=fuzF3",
    "description": "âœ¨ Quisque id justo sit amet sapien dignissim vestibulum. Donec posuere metus vitae ipsum. Nulla dapibus dolor vel est. Duis mattis egestas metus.",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Singapore",
    "joined_date": "May 9, 2022",
    "education": "B.A. Communications",
    "work": "Freelance Designer"
  },
  {
    "id": "5994914906",
    "firstName": "Nadia",
    "lastName": "Okonkwo",
    "username": "nokonkwo",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "nokonkwo@gmail.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=sZYKTp",
    "description": "Nulla ac enim. Fusce posuere felis sed lacus. Duis mattis egestas metus. Morbi ut odio. ðŸŒž",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "Sydney, AU",
    "joined_date": "May 12, 2024",
    "education": "M.Ed. Education",
    "work": "Operations Manager"
  },
  {
    "id": "0218613544",
    "firstName": "Idris",
    "lastName": "Windham",
    "username": "iwindham",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "iwindham@icloud.com",
    "avatar": "https://api.dicebear.com/10.x/lorelei/svg?skinColor=e4dcaa,e4d2aa,e4ccaa,c1ac95,d9cdb5,ebcf94,b9ae98&backgroundColor=b6e3f4,afeec5,afb1ee,c799a4&seed=mh0v",
    "description": "ðŸŒ¸ Duis mattis egestas metus. Aliquam non mauris. Fusce posuere felis sed lacus. ðŸ¶",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": "London, UK",
    "joined_date": "Jan 31, 2024",
    "education": "Certificate in UX Design",
    "work": "Full-Stack Developer"
  },
  {
    "id": "3082942060",
    "firstName": "Amara",
    "lastName": "Okoye",
    "username": "aokoye80",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "aokoye80@example.com",
    "avatar": "https://i.pravatar.cc/50?img=25",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "4409104618",
    "firstName": "Liam",
    "lastName": "Sorensen",
    "username": "lsorensen81",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "lsorensen81@example.com",
    "avatar": "https://i.pravatar.cc/50?img=15",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "9801599822",
    "firstName": "Elena",
    "lastName": "Vasquez",
    "username": "evasquez82",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "evasquez82@example.com",
    "avatar": "https://i.pravatar.cc/50?img=29",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "4170303198",
    "firstName": "Yuki",
    "lastName": "Tanaka",
    "username": "ytanaka83",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "ytanaka83@example.com",
    "avatar": "https://i.pravatar.cc/50?img=44",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "1027454692",
    "firstName": "Tobias",
    "lastName": "Krantz",
    "username": "tkrantz84",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "tkrantz84@example.com",
    "avatar": "https://i.pravatar.cc/50?img=52",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "4098147761",
    "firstName": "Neave",
    "lastName": "Waters",
    "username": "nwaters85",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "nwaters85@example.com",
    "avatar": "https://i.pravatar.cc/50?img=9",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "5669735400",
    "firstName": "Sofia",
    "lastName": "Reyes",
    "username": "sreyes86",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "sreyes86@example.com",
    "avatar": "https://i.pravatar.cc/50?img=5",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "5541352546",
    "firstName": "Raees",
    "lastName": "Warren",
    "username": "rwarren87",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "rwarren87@example.com",
    "avatar": "https://i.pravatar.cc/50?img=35",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "5440505903",
    "firstName": "Declan",
    "lastName": "Ferro",
    "username": "dferro88",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dferro88@example.com",
    "avatar": "https://i.pravatar.cc/50?img=33",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "1294491491",
    "firstName": "Marcus",
    "lastName": "Ilyin",
    "username": "milyin89",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "milyin89@example.com",
    "avatar": "https://i.pravatar.cc/50?img=12",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "8726679934",
    "firstName": "Dianna",
    "lastName": "Gibson",
    "username": "dgibson90",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "dgibson90@example.com",
    "avatar": "https://i.pravatar.cc/50?img=21",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "7470184896",
    "firstName": "Jane",
    "lastName": "Dorson",
    "username": "jdorson91",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jdorson91@example.com",
    "avatar": "https://i.pravatar.cc/50?img=25",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "6011867325",
    "firstName": "Priya",
    "lastName": "Anand",
    "username": "panand92",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "panand92@example.com",
    "avatar": "https://i.pravatar.cc/50?img=47",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  },
  {
    "id": "3674231566",
    "firstName": "Jack",
    "lastName": "Dorson",
    "username": "jdorson93",
    "password": "$2b$10$gwDhq3S2lihMq49sS1OL0.KfMszHGh8cCpxA5pR58C.KYeYCBR25u",
    "email": "jdorson93@example.com",
    "avatar": "https://i.pravatar.cc/50?img=21",
    "description": "",
    "job_title": null,
    "is_employee": false,
    "is_admin": false,
    "location": null,
    "joined_date": null,
    "education": null,
    "work": null
  }
];
module.exports = data;
